import { Inter } from "next/font/google";
import "./globals.css";

import ReduxProvider from "../components/provider/redux";
import { Suspense } from "react";
import useTheme from "@/hooks/useTheme";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
   title: "Emegen",
   description: "Generated by create next app",
};

export default async function Layout({ children }) {
   const currentTheme = await useTheme();

   return (
      <html lang="en" className={`${currentTheme} `}>
         <ReduxProvider>
            <body className={inter.className}>
               <Suspense>{children}</Suspense>
            </body>
         </ReduxProvider>
      </html>
   );
}
